server:
  port: 8888
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true


spring:
  datasource:
    username:
    password:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:database.db
  
  mail:
    host: smtp.163.com
    username: wenmingyan1990@163.com
    password: RIXAGJSHRQHPLHNG
    default-encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


mail:
  fromMail:
    sender: wenmingyan1990@163.com

application:
  name: 即时聊天
  magicNumber: 891013
  tempFilePath: /Users/Apple/Developer/DearIM/IM/uploadFiles/
  gitee:
    accessToken: 73e03449df0adc53bebcdb1ed5c8c9ea
    owner: mingyanwen
    repo: cloudStorage

mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1  # 逻辑已删除值（如布尔型字段设为 true 或整数型字段设为 1）
      logic-not-delete-value: 0  # 逻辑未删除值（如布尔型字段设为 false 或整数型字段设为 0）
      logic-delete-field: deleted  # 逻辑删除字段名
      id-type: AUTO

#  type-handlers-package: com.wmy.study.DearIMProject.typeHandler

logging:
  level:
    com.wmy.study.DearIMProject: debug

