server:
  port: 8888
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true


spring:
  datasource:
    username:
    password:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:/Users/apple/Developer/DearIM/IM/DearData/database.db
  
  mail:
    host: smtp.163.com
    username: wenmingyan1990@163.com
    password: RIXAGJSHRQHPLHNG
    default-encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


mail:
  fromMail:
    sender: wenmingyan1990@163.com

application:
  name: 展信佳
  magicNumber: 891013
  tempFilePath: /Users/Apple/Developer/DearIM/IM/uploadFiles/

mybatis-plus:
  global-config:
    db-config:
      id-type: AUTO

#  type-handlers-package: com.wmy.study.DearIMProject.typeHandler

logging:
  level:
    com.wmy.study.DearIMProject: debug

