server:
  port: 8888
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.99.103.133:3306/bookkeeping?useSSL=false
    username: admin
    password: wenmingyan
  mail:
    host: smtp.163.com
    username: wenmingyan1990@163.com
    password: RIXAGJSHRQHPLHNG
    default-encoding: UTF-8

mail:
  fromMail:
    sender: wenmingyan1990@163.com

application:
  name: 快记账
  magicNumber: 891013

mybatis-plus:
  global-config:
    db-config:
      id-type: AUTO

logging:
  level:
    com.wmy.study.DearIMProject: debug
